### Homework

Set up the environment
You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can the instructions from 06-environment.md.

## Question 1

What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

`pd.__version__`


In [2]:
import pandas as pd

In [3]:
pd.__version__

'1.4.4'

### Getting the data
For this homework, we'll use the California Housing Prices dataset. Download it from here.

You can do it with wget:

wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Or just open it with your browser and click "Save as...".

Now read it with Pandas.



In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-18 10:00:42--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: 'housing.csv'

housing.csv         100%[===================>]   1.36M  7.10MB/s    in 0.2s    

2023-09-18 10:00:44 (7.10 MB/s) - 'housing.csv' saved [1423529/1423529]



In [6]:
df = pd.read_csv('housing.csv')

## Question 2
How many columns are in the dataset?

* 10 (+)
* 6560
* 10989
* 20640

In [8]:
df.shape

(20640, 10)

In [11]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


## Question 3
Which columns in the dataset have missing values?

* total_rooms
* total_bedrooms (+)
* both of the above
* no empty columns in the dataset

In [14]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

## Question 4
How many unique values does the __ocean_proximity__ column have?

* 3
* 5 (+)
* 7
* 9


In [15]:
df['ocean_proximity'].value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

In [16]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [17]:
len(df['ocean_proximity'].unique())

5

## Question 5
What's the average value of the __median_house_value__ for the houses located near the bay?

* 49433
* 124805
* 259212 (+)
* 380440

In [22]:
df['median_house_value'].describe()

count     20640.000000
mean     206855.816909
std      115395.615874
min       14999.000000
25%      119600.000000
50%      179700.000000
75%      264725.000000
max      500001.000000
Name: median_house_value, dtype: float64

In [23]:
df['median_house_value'].mean()

206855.81690891474

In [25]:
df[df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean()

259212.31179039303

## Question 6
1. Calculate the average of __total_bedrooms__ column in the dataset.
2. Use the fillna method to fill the missing values in __total_bedrooms__ with the mean value from the previous step.
3. Now, calculate the average of __total_bedrooms__ again.
4. Has it changed?
Has it changed?

Hint: take into account only 3 digits after the decimal point.

* Yes
* No (+)


In [35]:
total_bedrooms_mean = df['total_bedrooms'].mean()
print(round(total_bedrooms_mean, 3))

537.871


In [36]:
df_filled_total_bedrooms = df['total_bedrooms'].fillna(total_bedrooms_mean)

In [37]:
round(df_filled_total_bedrooms.mean(), 3)

537.871

In [43]:
avg = float(df_filled_total_bedrooms.mean())
print(f'Average total_bedrooms is {avg:.3f}')

Average total_bedrooms is 537.871


## Question 7
1. Select all the options located on islands.
2. Select only columns housing_median_age, total_rooms, total_bedrooms.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [950, 1300, 800, 1000, 1300].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the last element of w?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

* -1.4812
* 0.001
* 5.6992 (+)
* 23.1233

In [44]:
df_train = df[df['ocean_proximity'] == 'ISLAND'][["housing_median_age", "total_rooms", "total_bedrooms"]].reset_index(drop=True)

In [45]:
df_train

housing_median_age  total_rooms  total_bedrooms
0                27.0       1675.0           521.0
1                52.0       2359.0           591.0
2                52.0       2127.0           512.0
3                52.0        996.0           264.0
4                29.0        716.0           214.0

In [48]:
import numpy as np
X = np.array(df_train)

In [49]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [50]:
y = np.array([950, 1300, 800, 1000, 1300])

In [51]:
y

array([ 950, 1300,  800, 1000, 1300])

In [52]:
XTX = X.T @ X

In [54]:
XTX_inv = np.linalg.inv(XTX)

In [55]:
w = XTX_inv @ X.T @ y

In [56]:
w

array([23.12330961, -1.48124183,  5.69922946])

In [57]:
w[-1]

5.699229455065575